# Example API configuration file
# This file defines the engine type, model name, and inference parameters for API-based inference

engine: "claude_reason_api"
model_name: "claude-sonnet-4"
use_cache: true

api_key: "sk-xxx"

infer_cfgs:
  # Sampling parameters (now configurable!)
  #temperature: 0.05
  max_tokens: 4096
  #top_p: 0.9
  #top_k: 50
  #frequency_penalty: 0.0
  #presence_penalty: 0.0

# Note: model_cfgs is not used for API engine
model_cfgs:
  model: "claude-sonnet-4"