# Example API configuration file
# This file defines the engine type, model name, and inference parameters for API-based inference

engine: "reason_api"
model_name: 'gpt-5'
use_cache: true

api_key: "sk-xxx"

infer_cfgs:
  # Sampling parameters (now configurable!)
  #temperature: 0.05
  max_output_tokens: 8192
  #top_p: 0.9
  #top_k: 50
  #frequency_penalty: 0.0
  #presence_penalty: 0.0

# Note: model_cfgs is not used for API engine
model_cfgs:
  model: "gpt-5"